DELETE FROM PUBLIC.TICKETS;
DELETE FROM PUBLIC.INFLIGHTSRESERVATIONS;
DELETE FROM PUBLIC.OUTFLIGHTSRESERVATIONS;
DELETE FROM PUBLIC.RESERVATIONS;
DELETE FROM PUBLIC.FLIGHTS;
DELETE FROM PUBLIC.AIRPORTS;
DELETE FROM PUBLIC.ACCOUNTMANAGEMENT;

INSERT INTO PUBLIC.TICKETS(FLIGHTID, LUGGAGEINCLUDED, PIECES, RESERVATIONID, TICKETID, WEIGHT, TICKETPRICE, PASSPORTID, FIRSTNAME, LASTNAME, SEATNO) VALUES (25, 'FALSE', 0, 25, 0, 100, 'CP152D45', 'Bob', 'Wonder', '1A');
INSERT INTO PUBLIC.TICKETS(FLIGHTID, LUGGAGEINCLUDED, PIECES, RESERVATIONID, TICKETID, WEIGHT, TICKETPRICE, PASSPORTID, FIRSTNAME, LASTNAME, SEATNO) VALUES (26, 'FALSE', 0, 26, 0, 80, 'AB42J34D', 'Art', 'Buster', '2F');

INSERT INTO PUBLIC.INFLIGHTSRESERVATIONS(FLIGHTID, RESERVATIONID) VALUES (27, 27);
INSERT INTO PUBLIC.OUTFLIGHTSRESERVATIONS(FLIGHTID, RESERVATIONID) VALUES (27, 27);

INSERT INTO PUBLIC.RESERVATIONS(BOOKINGID, PASSENGERID, RETURNFLIGHT, TOTALPRICE) VALUES (27, 54, 'FALSE', 100);
INSERT INTO PUBLIC.RESERVATIONS(BOOKINGID, PASSENGERID, RETURNFLIGHT, TOTALPRICE) VALUES (28, 55, 'TRUE', 280);

INSERT INTO PUBLIC.FLIGHTS(AIRCRAFTCAPACITY, AIRLINEID, ARRAIRPORTID, AVAILABLESEATS, DEPAIRPORTID, ID, TICKETPRICE, ARRTIME, DEPTIME, FLIGHTNO, AIRCRAFTTYPE) VALUES (200, 56, 29, 199, 27, 28, 100, null, null);

INSERT INTO PUBLIC.AIRPORTS(AIRPORTID, U3DIGITCODE, CITY, COUNTRY, NAME) VALUES (29, 'ATH', 'Athens', 'Greece', 'Eleftherios Venizelos');
INSERT INTO PUBLIC.AIRPORTS(AIRPORTID, U3DIGITCODE, CITY, COUNTRY, NAME) VALUES (30, 'JAP', 'Asakusa', 'Kyoto', 'Kyoto Airlines');

INSERT INTO PUBLIC.ACCOUNTMANAGEMENT(ID, U2DIGITCODE, ADMIN_ID, EMAIL, PASSPORT_ID, PASSWORD, PHONENUM, USERNAME, NAME, TYPE) VALUES (57, 'JA', 'Supreme', 'electromommy@aueb.gr', 'SK123404', 'LimboHen2@', '6944120412', 'Yae_Miko', 'Kyoto Air', 'ADMINISTRATOR');











