-- Delete the data from the database for initialization purposes
DELETE FROM PUBLIC.TICKETS;
DELETE FROM PUBLIC.INFLIGHTSRESERVATIONS;
DELETE FROM PUBLIC.OUTFLIGHTSRESERVATIONS;
DELETE FROM PUBLIC.RESERVATIONS;
DELETE FROM PUBLIC.FLIGHTS;
DELETE FROM PUBLIC.AIRPORTS;
DELETE FROM PUBLIC.ACCOUNTMANAGEMENT;


INSERT INTO PUBLIC.AIRPORTS(AIRPORTID, U3DIGITCODE, CITY, COUNTRY, NAME) VALUES (33, 'USA', 'Las_Vegas', 'America', 'America Airlines');
INSERT INTO PUBLIC.AIRPORTS(AIRPORTID, U3DIGITCODE, CITY, COUNTRY, NAME) VALUES (30, 'JAP', 'Asakusa', 'Kyoto', 'Kyoto Airlines');

INSERT INTO PUBLIC.ACCOUNTMANAGEMENT(ID, U2DIGITCODE, ADMIN_ID, EMAIL, PASSPORT_ID, PASSWORD, PHONENUM, USERNAME, NAME, TYPE) VALUES (57, 'JA', 'Supreme', 'electromommy@aueb.gr', 'SK123404', 'LimboHen2@', '6944120412', 'Yae_Miko', 'Kyoto Air', 'ADMINISTRATOR');
INSERT INTO PUBLIC.ACCOUNTMANAGEMENT(ID, U2DIGITCODE, ADMIN_ID, EMAIL, PASSPORT_ID, PASSWORD, PHONENUM, USERNAME, NAME, TYPE) VALUES (56, 'A3',NULL,NULL,NULL,'JeandDig1@',NULL,'aegean','Aegean Airlines','AIRLINE')
INSERT INTO PUBLIC.ACCOUNTMANAGEMENT(ID, U2DIGITCODE, ADMIN_ID, EMAIL, PASSPORT_ID, PASSWORD, PHONENUM, USERNAME, NAME, TYPE) VALUES (58, NULL,NULL,'ndiam@aueb.gr','AK102545','JeandDig1@','1234567891','ndiam',null,'PASSENGER')


INSERT INTO PUBLIC.RESERVATIONS(BOOKINGID, PASSENGERID, RETURNFLIGHT, TOTALPRICE) VALUES (27, 58, 'FALSE', 100);
INSERT INTO PUBLIC.RESERVATIONS(BOOKINGID, PASSENGERID, RETURNFLIGHT, TOTALPRICE) VALUES (28, 58, 'TRUE', 280);

INSERT INTO PUBLIC.FLIGHTS(AIRCRAFTCAPACITY, AIRLINEID, ARRAIRPORTID, AVAILABLESEATS, DEPAIRPORTID, ID, TICKETPRICE, ARRTIME, DEPTIME, FLIGHTNO, AIRCRAFTTYPE) VALUES (200, 56, 33, 199, 30, 28, 100, null, null, 'US4520', 'RyanAir-220');

INSERT INTO PUBLIC.TICKETS(FLIGHTID, LUGGAGEINCLUDED, PIECES, RESERVATIONID, TICKETID, WEIGHT, TICKETPRICE, PASSPORTID, FIRSTNAME, LASTNAME, SEATNO) VALUES (28, 'FALSE', 0, 28, 28, 0, 100, 'CP162D45', 'Bobby', 'Wonders', '1B');

INSERT INTO PUBLIC.INFLIGHTSRESERVATIONS(FLIGHTID, RESERVATIONID) VALUES (27, 28);
INSERT INTO PUBLIC.OUTFLIGHTSRESERVATIONS(FLIGHTID, RESERVATIONID) VALUES (28, 28);













