-- Delete the data from the database for initialization purposes
DELETE FROM PUBLIC.TICKETS;
DELETE FROM PUBLIC.INFLIGHTSRESERVATIONS;
DELETE FROM PUBLIC.OUTFLIGHTSRESERVATIONS;
DELETE FROM PUBLIC.RESERVATIONS;
DELETE FROM PUBLIC.FLIGHTS;
DELETE FROM PUBLIC.AIRPORTS;
DELETE FROM PUBLIC.ACCOUNTMANAGEMENT;

-- The first four tables and linked with foreign key dependency, so be careful when inserting the new data

INSERT INTO PUBLIC.TICKETS(FLIGHTID, LUGGAGEINCLUDED, PIECES, RESERVATIONID, TICKETID, WEIGHT, TICKETPRICE, PASSPORTID, FIRSTNAME, LASTNAME, SEATNO) VALUES (28, 'FALSE', 0, 28, 28, 0, 100, 'CP162D45', 'Bobby', 'Wonders', '1B');

INSERT INTO PUBLIC.INFLIGHTSRESERVATIONS(FLIGHTID, RESERVATIONID) VALUES (27, 28);
INSERT INTO PUBLIC.OUTFLIGHTSRESERVATIONS(FLIGHTID, RESERVATIONID) VALUES (28, 28);

INSERT INTO PUBLIC.FLIGHTS(AIRCRAFTCAPACITY, AIRLINEID, ARRAIRPORTID, AVAILABLESEATS, DEPAIRPORTID, ID, TICKETPRICE, ARRTIME, DEPTIME, FLIGHTNO, AIRCRAFTTYPE) VALUES (200, 56, 28, 199, 27, 28, 100, null, null, 'US4520', 'RyanAir-220');

-- As for the other tables, you may insert them from the start

INSERT INTO PUBLIC.RESERVATIONS(BOOKINGID, PASSENGERID, RETURNFLIGHT, TOTALPRICE) VALUES (27, 54, 'FALSE', 100);
INSERT INTO PUBLIC.RESERVATIONS(BOOKINGID, PASSENGERID, RETURNFLIGHT, TOTALPRICE) VALUES (28, 55, 'TRUE', 280);

INSERT INTO PUBLIC.AIRPORTS(AIRPORTID, U3DIGITCODE, CITY, COUNTRY, NAME) VALUES (32, 'USA', 'Las_Vegas', 'America', 'America Airlines');
INSERT INTO PUBLIC.AIRPORTS(AIRPORTID, U3DIGITCODE, CITY, COUNTRY, NAME) VALUES (30, 'JAP', 'Asakusa', 'Kyoto', 'Kyoto Airlines');

INSERT INTO PUBLIC.ACCOUNTMANAGEMENT(ID, U2DIGITCODE, ADMIN_ID, EMAIL, PASSPORT_ID, PASSWORD, PHONENUM, USERNAME, NAME, TYPE) VALUES (57, 'JA', 'Supreme', 'electromommy@aueb.gr', 'SK123404', 'LimboHen2@', '6944120412', 'Yae_Miko', 'Kyoto Air', 'ADMINISTRATOR');











